config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'


  get 'about' => 'welcome#about', as: :about
  get 'coaching' => 'welcome#coaching', as: :coaching


  get 'guestmacros' => 'macros#guest_macros', as: :guest_macros
  post 'guestmacros' => 'macros#guest_macros'

  get 'macros' => 'macros#show', as: :macros
  get 'macros/edit' => 'macros#edit', as: :edit_macros
  patch 'macros/edit' => 'macros#update'
  patch 'macros/up' => 'macros#notch_up', as: :notch_up
  patch 'macros/down' => 'macros#notch_down', as: :notch_down


  post 'mealplans' => 'mealplans#auto_mealplans', as: :auto_mealplans
  patch 'mealplans/generate/:id' => 'mealplans#generate', as: :generate_mealplan
  get 'mealplans' => 'mealplans#list', as: :mealplans
  post 'mealplans' => 'mealplans#new', as: :new_mealplan
  get 'mealplans/:id' => 'mealplans#show', as: :mealplan
  get 'mealplans/edit/:id' => 'mealplans#edit', as: :edit_mealplan
  delete 'mealplans/:id' => 'mealplans#delete_mealplan', as: :delete_mealplan
  patch 'mealplans/edit/:id' => 'mealplans#add_meal', as: :add_meal
  delete 'mealplans/:id/meals/:meal_id' => 'mealplans#delete_meal', as: :delete_meal


  get 'meal/:id' => 'food#show_meal', as: :meal
  get 'ingredient/:id' => 'food#show_ingredient', as: :ingredient
  get 'mealcenter' => 'food#mealcenter', as: :mealcenter
  get 'foodfinder' => 'food#finder', as: :food_finder
  post 'foodfinder' => 'food#search', as: :search_food
  post 'favorites' => 'food#add_favorite', as: :add_favorite
  get 'favorites' => 'food#favorites', as: :favorites
  delete 'favorites/:id' => 'food#delete_favorite', as: :delete_favorite
  get 'recipecollections' => 'food#recipe_collections', as: :recipe_collections
  get 'recipe/:id' => 'food#show_recipe', as: :recipe


  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user
  get 'profile' => 'users#profile', as: :user_profile
  get 'profile/edit' => 'users#edit_profile', as: :edit_profile
  patch 'profile/edit' => 'users#update_profile'


  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#destroy'





end

app/models/food.rb
require "openssl"
require "base64"
require "digest/md5"
require "net/http"
require 'cgi'

class Food < ActiveRecord::Base
    # attr_accessible :title, :body

    KEY = '2858c7582362405f83adf083b332bde6'.freeze
    SECRET = '67e241faea4c4f6abdc48bd99edc4bb2'.freeze
    SHA1 = 'HMAC-SHA1'.freeze
    SITE = 'http://platform.fatsecret.com/rest/server.api'.freeze
    class String
        def esc
            CGI.escape(self).gsub('%7E', '~').gsub('+', '%20')
        end
    end
    def self.search(expression)
        params = {
            oauth_consumer_key: KEY,
            oauth_nonce: Digest::MD5.hexdigest(rand(11).to_s),
            oauth_signature_method: SHA1,
            oauth_timestamp: Time.now.to_i,
            oauth_version: '1.0',
            method: 'foods.search',
            format: 'json',
            search_expression: expression.esc
        }
        sorted_params = params.sort { |a, b| a.first.to_s <=> b.first.to_s }
        base = base_string('GET', sorted_params)
        http_params = http_params('GET', params)
        sig = sign(base).esc
        uri = uri_for(http_params, sig)
        results = Net::HTTP.get(uri)
    end
    def self.get(food_id)
        params = {
            oauth_consumer_key: KEY,
            oauth_nonce: Digest::MD5.hexdigest(rand(11).to_s),
            oauth_signature_method: SHA1,
            oauth_timestamp: Time.now.to_i,
            oauth_version: '1.0',
            method: 'food.get',
            food_id: food_id,
            format: 'json'
        }
        sorted_params = params.sort { |a, b| a.first.to_s <=> b.first.to_s }
        base = base_string('GET', sorted_params)
        http_params = http_params('GET', params)
        sig = sign(base).esc
        uri = uri_for(http_params, sig)
        results = Net::HTTP.get(uri)
    end

    def self.base_string(http_method, param_pairs)
        param_str = param_pairs.collect { |pair| "#{pair.first}=#{pair.last}" }.join('&')
        list = [http_method.esc, SITE.esc, param_str.esc]
        list.join('&')
    end

    def self.http_params(_method, args)
        pairs = args.sort { |a, b| a.first.to_s <=> b.first.to_s }
        list = []
        pairs.inject(list) { |arr, pair| arr << "#{pair.first}=#{pair.last}" }
        list.join('&')
    end

    def self.sign(base, token = '')
        secret = "#{SECRET.esc}&#{token.esc}"
        base64 = Base64.encode64(OpenSSL::HMAC.digest('sha1', secret, base)).delete("\n")
    end

    def self.uri_for(params, signature)
        parts = params.split('&')
        parts << "oauth_signature=#{signature}"
        URI.parse("#{SITE}?#{parts.join('&')}")
    end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController

  before_action :authenticate_user!

  def mealcenter
  end

  def favorites
    @favorites = Recipe.where category: (@current_user.id).to_s
  end

  def delete_favorite
    @recipe = Recipe.find_by category: (@current_user.id).to_s
    @recipepart = Recipepart.find_by recipe_id: @recipe.id
    @ingredient = Ingredient.find_by id: @recipepart.ingredient_id

    @ingredient.destroy
    @recipe.destroy
    @recipepart.destroy

    redirect_to favorites_path, notice: "Favorite Deleted"
  end

  def finder
  end

  def recipe_collections
    @recipes = Recipe.where.not("category ~* ?", "^[0-9]")
  end

  def search

    response = JSON.parse(Food.search(params[:query]))

    if response["foods"]["total_results"] == "0"
      redirect_to food_finder_path, notice: "Food not found!"
    else

      if response["foods"]["food"].kind_of?(Array)
        food_id = response["foods"]["food"].first["food_id"]
        @food_brand = response["foods"]["food"].first["brand_name"]
        @food_name = response["foods"]["food"].first["food_name"]
      else
        food_id = response["foods"]["food"]["food_id"]
        @food_brand = response["foods"]["food"]["brand_name"]
        @food_name = response["foods"]["food"]["food_name"]
      end

      details = JSON.parse(Food.get(food_id))

      if details["food"]["servings"]["serving"].kind_of?(Array)
        @food_calories = details["food"]["servings"]["serving"][0]["calories"].to_i
        @food_protein = details["food"]["servings"]["serving"][0]["protein"].to_i
        @food_carbohydrate = details["food"]["servings"]["serving"][0]["carbohydrate"].to_i
        @food_fat = details["food"]["servings"]["serving"][0]["fat"].to_i
        @food_serving = details["food"]["servings"]["serving"][0]["serving_description"]
        @food_weight = details["food"]["servings"]["serving"][0]["metric_serving_amount"].to_i
        @food_weight_unit = details["food"]["servings"]["serving"][0]["metric_serving_unit"]

      else
        @food_serving = details["food"]["servings"]["serving"]["serving_description"]
        @food_calories = details["food"]["servings"]["serving"]["calories"].to_i
        @food_protein = details["food"]["servings"]["serving"]["protein"].to_i
        @food_carbohydrate = details["food"]["servings"]["serving"]["carbohydrate"].to_i
        @food_fat = details["food"]["servings"]["serving"]["fat"].to_i
        @food_serving = details["food"]["servings"]["serving"]["serving_description"]
        @food_weight = details["food"]["servings"]["serving"]["metric_serving_amount"].to_i
        @food_weight_unit = details["food"]["servings"]["serving"]["metric_serving_unit"]
      end

      render :finder
    end
  end

  def add_favorite
    @ingredient = Ingredient.new
    @ingredient.serving_amount = 1
    @ingredient.serving_name = params[:serving]
    @ingredient.calories = params[:calories]
    @ingredient.protein = params[:protein]
    @ingredient.carbs = params[:carbs]
    @ingredient.fat = params[:fat]
    name = "#{params[:brand]} #{params[:name]}"
    @ingredient.name = name
    @ingredient.save


    @recipe = Recipe.new
    @recipe.category = (@current_user.id).to_s
    @recipe.name = name
    @recipe.description = "One of your favorite foods! Fit it into your Meal Plans!"
    @recipe.collection = "Favorites"
    @recipe.save


    @recipepart = Recipepart.new
    @recipepart.ingredient_id = @ingredient.id
    @recipepart.recipe_id = @recipe.id
    @recipepart.amount = 1
    @recipepart.save


    if params[:name] =~ /^\s*$/
      redirect_to food_finder_path, notice: "You didn't seach anything"
    elsif @ingredient.save && @recipe.save && @recipepart.save
      redirect_to food_finder_path, notice: "Added #{@ingredient.name} to your favorites!"
    else
      redirect_to food_finder_path, notice: "Something went wrong"
    end
  end

  def show_meal
    @meal = Meal.find_by id: params[:id]
  end

  def show_recipe
    @recipe = Recipe.find_by id: params[:id]
  end

  def show_ingredient
    @ingredient = Ingredient.find_by id: params[:id]
  end

end

#stuff I might need for making the servings dropdown ###
# @food_info = details["food"]["servings"]["serving"]
# serving_description, calories, protein, carbohydrate, fat, metric_serving_amount, metric_serving_unit = [], [], [], [], [], [], []
#
# @food_info.each do |food|
#   serving_description << food["serving_description"]
#   calories << food["calories"]
#   protein << food["protein"]
#   carbohydrate << food["carbohydrate"]
#   fat << food["fat"]
#   metric_serving_amount << food["metric_serving_amount"]
#   metric_serving_unit << food["metric_serving_unit"]
# end

app/views/food/favorites.html.erb
<div class="container">
  <br>
  <div class="wow animated fadeIn text-center" data-wow-delay="0.1s">
    <h2 class="mealplan-title mealplan-title-bottom-padding">Your Favorite Foods</h2>
  </div>
  <br>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-6 margin30 meals">
        <div class="wow animated fadeIn" data-wow-delay="0.15s">
          <% @favorites.each do |favorite| %>
            <strong class="meal-title">
            <%=favorite.name %>
            <small>
              <%= link_to "x", delete_favorite_path(favorite.id), method: :delete %>
            </small> <br>
            </strong>
            <span class="meal-body">
          <%= favorite.recipeparts.first.ingredient_id %><br>
          <%= number_to_human(favorite.kcals) %> kcals<br>
          <%= number_to_human(favorite.proteins) %>g Protein<br>
          <%= number_to_human(favorite.carbs) %>g Carbs<br>
          <%= number_to_human(favorite.fats) %>g Fat<br></span>

          <hr class="form-divider">
            <% end %>
        </div>
      </div>
    </div>
</div>

app/views/food/finder.html.erb
<div class="container">
  <br>
  <div class="wow animated fadeIn text-center" data-wow-delay="0.05s">
    <h2 class="mealplan-title mealplan-title-bottom-padding">Search for your favorite food</h2>
  </div>
  <div class="form-group wow animated fadeIn text-center" data-wow-delay="0.1s">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
              <%= form_tag search_food_path do %>
        <div class="form-group">
            <%= text_field_tag(:query, params[:query], class: "form-control", placeholder: "Enter Food Name") %>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="col-xs-6 col-sm-offset-2 col-sm-4">
          <div class="form-group">
              <%= submit_tag("Search", class: "btn btn-block btn-danger") %>
          </div>
        </div>
      <% end %>



        <%= form_tag add_favorite_path do %>

        <div class="col-xs-6 col-sm-4">
          <div class="form-group">
              <%= submit_tag "Add to Favorites!", class:'btn btn-success btn-block' %>
          </div>
        </div>
      </div>
    </div>
        <div class="row hidden-form">
          <div class="form-group">
              <%= label_tag :name %>
              <%= text_field_tag :name, @food_name %>
          </div>
          <div class="form-group">
              <%= label_tag :brand %>
              <%= text_field_tag :brand, @food_brand %>
          </div>
          <div class="form-group">
              <%= label_tag :calories %>
              <%= number_field_tag :calories, @food_calories %>
          </div>
          <div class="form-group">
              <%= label_tag :protein %>
              <%= number_field_tag :protein, @food_protein %>
          </div>
          <div class="form-group">
              <%= label_tag :carbs %>
              <%= number_field_tag :carbs, @food_carbohydrate %>
          </div>
          <div class="form-group">
              <%= label_tag :fat %>
              <%= number_field_tag :fat, @food_fat %>
          </div>
          <div class="form-group">
              <%= label_tag :serving %>
              <%= text_field_tag :serving, @food_serving %>
          </div>
        </div>
        <% end %>




<br>
<br>

<div class="container">
  <div class="row">
    <div class="text-center">
      <div class="col-sm-6 col-sm-offset-3 margin30">
        <% if @food_name %>
        <div class="service-box wow animated fadeIn" data-wow-delay="0.2s">
          <i class="fa fa-cutlery" aria-hidden="true"></i>

            <h3 class="food-search-title">Seach Results</h3>

              <strong class="food-search-name"><%= @food_name %></strong> <br>
              <% if @food_brand %>
                Brand: <%= @food_brand %> <br>
              <% end %>
              <%= @food_serving %> (<%= @food_weight %> <%= @food_weight_unit %>) <br>
              <%= @food_calories %> Calories <br>
              <%= number_to_human(@food_protein) %>g Protein <br>
              <%= number_to_human(@food_carbohydrate) %>g Carbs <br>
              <%= number_to_human(@food_fat) %>g Fat <br>

               <br>
        </div>
      </div><!--service column-->
          <% end %>
    </div>



  </div>
</div>

app/views/food/mealcenter.html.erb
<br>
  <div class="container">
      <div class="row center-title">
        <br>
          <div class="col-md-8 col-md-offset-2 clearfix text-center wow animated fadeInUp">
              <h2>The Meal Center</h2>
              <p>
                Instant access to everything food related!
              </p>
          </div>
      </div><!--service column-->

      <div class="row">
          <%= link_to mealplans_path do %>
          <div class="col-sm-6 col-md-3 margin30">
              <div class="service-box wow animated fadeIn home-box-size" data-wow-delay="0.1s">
                <i class="fa fa-files-o" aria-hidden="true"></i>
                  <h4>My Meal Plans</h4>
                  <p>
                    Your roadmaps to success.
                    Automatically create Meal Plans from recipe collections and edit them as you please!
                  </p>
              </div>
          </div><!--service column-->
          <% end %>

          <%= link_to recipe_collections_path do %>
          <div class="col-sm-6 col-md-3 margin30">
              <div class="service-box wow animated fadeIn home-box-size" data-wow-delay="0.2s">
                <i class="fa fa-book" aria-hidden="true"></i>
                  <h4>Recipe Collections</h4>
                  <p>
                    Whether you're into making everything in a crockpot,
                    microwave or have an insatiable love for breakfast foods,
                    we've got a collection of healthy recipes for you.
              </div>
          </div><!--service column-->
          <% end %>

          <%= link_to food_finder_path do %>
          <div class="col-sm-6 col-md-3 margin30">
              <div class="service-box wow animated fadeIn home-box-size" data-wow-delay="0.3s">
                <i class="fa fa-search" aria-hidden="true"></i>
                  <h4>Food Finder</h4>
                  <p>
                    Search for your favorite foods and save them. Then you'll be able to add them to your Meal Plans!
                  </p>
              </div>
          </div><!--service column-->
          <% end %>
          <%= link_to favorites_path do %>
          <div class="col-sm-6 col-md-3 margin30">
              <div class="service-box wow animated fadeIn home-box-size" data-wow-delay="0.4s">
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <h4>Your Favorites</h4>
                  <p>
                    This is your own personal pantry for your favorite food items.
                  </p>
              </div>
          </div><!--service column-->
          <% end %>

      </div>

app/views/food/recipe_collections.html.erb
<div class="container">
  <br>
  <div class="wow animated fadeIn text-center" data-wow-delay="0.1s">
    <h2 class="mealplan-title mealplan-title-bottom-padding">Recipe Collections <br> <small>(More coming soon!)</small></h2>
  </div>
  <br>

    <div class="row">
      <h2 class="text-center wow animated fadeIn" data-wow-delay="0.2s">Breakfast Lovers!</h2>
      <div class="col-sm-6 col-sm-offset-6 margin30 meals">
        <div class="wow animated fadeIn" data-wow-delay="0.3s">
          <% @recipes.each do |recipe| %>
            <strong class="meal-title">
              <%= link_to recipe.name, recipe_path(id:recipe.id) %> <br>
            </strong>
            <span class="meal-body">
              <% recipe.recipeparts.each do |part| %>
            <%= number_to_human(part.amount * part.ingredient.serving_amount) %>  <%= part.ingredient.serving_name %> <%= part.ingredient.name %> <br>
              <% end %>
          <em> <%= number_to_human(recipe.kcals) %> kcals -
          <%= number_to_human(recipe.proteins).to_i %>g P -
          <%= number_to_human(recipe.carbs).to_i %>g C -
          <%= number_to_human(recipe.fats).to_i %>g F </em></span>

          <hr class="form-divider">
            <% end %>
        </div>
      </div>
    </div>
</div>

app/views/food/show_ingredient.html.erb
<div class="container">

  <div class="row text-center">
  <h2><%= @ingredient.name %></h2>
  </div>

</div>

app/views/food/show_meal.html.erb
<div class="container">
<br>

  <div class="row">
    <div class="text-center">
      <h2 class="mealplan-title"> <%= @meal.recipe.name %></h2>
    </div>
  </div>


<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 margin30">
    <div class="service-box wow animated fadeIn" data-wow-delay="0.1s">
        <h4>Ingredients</h4>
        <br>
        <% @meal.recipe.recipeparts.each do |r| %>
            <h5>
            <%= pluralize(number_to_human((r.amount * r.ingredient.serving_amount) * @meal.quantity), r.ingredient.serving_name)  %>
            -
            <%=r.ingredient.name%>
          </h5>
        <% end %>
        Approx:
        <%= number_to_human(@meal.recipe.kcals * @meal.quantity) %>kcal -
        <%= number_to_human(@meal.recipe.proteins * @meal.quantity) %>P -
        <%= number_to_human(@meal.recipe.carbs * @meal.quantity) %>C -
        <%= number_to_human(@meal.recipe.fats * @meal.quantity) %>F
        <p></p>
    </div>
  </div><!--service column-->
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 margin30">
    <div class="wow animated fadeIn" data-wow-delay="0.2s">
        <h3>Directions:</h3>
      <span class="bigger-text"><%= simple_format(@meal.recipe.description) %></span>
    </div>
  </div><!--service column-->
</div>


    <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
        <%= link_to mealplan_path(id: @meal.mealplan_id) do %>
        <div class="btn btn-success btn-block button-bottom-margin">
          Back
        </div>
        <% end %>
      </div>
    </div>
</div>

app/views/food/show_recipe.html.erb
<div class="container">
<br>

  <div class="row">
    <div class="text-center">
      <h2 class="mealplan-title"> <%= @recipe.name %></h2>
    </div>
  </div>


<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 margin30">
    <div class="service-box wow animated fadeIn" data-wow-delay="0.1s">
        <h4>Ingredients</h4>
        <br>
        <% @recipe.recipeparts.each do |r| %>
            <h5>
            <%= pluralize(number_to_human(r.amount * r.ingredient.serving_amount), r.ingredient.serving_name)  %>
            -
            <%=r.ingredient.name%>
          </h5>
        <% end %>
        Approx:
        <%= number_to_human(@recipe.kcals ) %>kcal -
        <%= number_to_human(@recipe.proteins ) %>P -
        <%= number_to_human(@recipe.carbs ) %>C -
        <%= number_to_human(@recipe.fats ) %>F
        <p></p>
    </div>
  </div><!--service column-->
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 margin30">
    <div class="wow animated fadeIn" data-wow-delay="0.2s">
        <h3>Directions:</h3>
      <span class="bigger-text"><%= simple_format(@recipe.description) %></span>
    </div>
  </div><!--service column-->
</div>


    <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
        <%= link_to recipe_collections_path do %>
        <div class="btn btn-success btn-block button-bottom-margin">
          Back
        </div>
        <% end %>
      </div>
    </div>
</div>