config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'


  get 'about' => 'welcome#about', as: :about
  get 'coaching' => 'welcome#coaching', as: :coaching


  get 'guestmacros' => 'macros#guest_macros', as: :guest_macros
  post 'guestmacros' => 'macros#guest_macros'

  get 'macros' => 'macros#show', as: :macros
  get 'macros/edit' => 'macros#edit', as: :edit_macros
  patch 'macros/edit' => 'macros#update'
  patch 'macros/up' => 'macros#notch_up', as: :notch_up
  patch 'macros/down' => 'macros#notch_down', as: :notch_down


  post 'mealplans' => 'mealplans#auto_mealplans', as: :auto_mealplans
  patch 'mealplans/generate/:id' => 'mealplans#generate', as: :generate_mealplan
  get 'mealplans' => 'mealplans#list', as: :mealplans
  post 'mealplans' => 'mealplans#new', as: :new_mealplan
  get 'mealplans/:id' => 'mealplans#show', as: :mealplan
  get 'mealplans/edit/:id' => 'mealplans#edit', as: :edit_mealplan
  delete 'mealplans/:id' => 'mealplans#delete_mealplan', as: :delete_mealplan
  patch 'mealplans/edit/:id' => 'mealplans#add_meal', as: :add_meal
  delete 'mealplans/:id/meals/:meal_id' => 'mealplans#delete_meal', as: :delete_meal


  get 'meal/:id' => 'food#show_meal', as: :meal
  get 'ingredient/:id' => 'food#show_ingredient', as: :ingredient
  get 'mealcenter' => 'food#mealcenter', as: :mealcenter
  get 'foodfinder' => 'food#finder', as: :food_finder
  post 'foodfinder' => 'food#search', as: :search_food
  post 'favorites' => 'food#add_favorite', as: :add_favorite
  get 'favorites' => 'food#favorites', as: :favorites
  delete 'favorites/:id' => 'food#delete_favorite', as: :delete_favorite
  get 'recipecollections' => 'food#recipe_collections', as: :recipe_collections
  get 'recipe/:id' => 'food#show_recipe', as: :recipe


  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user
  get 'profile' => 'users#profile', as: :user_profile
  get 'profile/edit' => 'users#edit_profile', as: :edit_profile
  patch 'profile/edit' => 'users#update_profile'


  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#destroy'





end

app/controllers/macros_controller.rb
class MacrosController < ApplicationController

  before_action :authenticate_user!, :except => [:guest_macros]

  before_action :except => [:guest_macros] do
    if @current_user.age.nil? || @current_user.weight.nil?
      redirect_to edit_profile_path, alert: "We're gonna need your stats first!"
    end
  end


  def guest_macros

    if params[:age] == "" || params[:weight] == ""
      redirect_to guest_macros_path, notice: "You left either Age or Weight blank"
    end

    macroparser = GuestMacroParser.new(params)
    macroparser.parse!


    @fat = macroparser.fat
    @protein = macroparser.protein
    @carbs = macroparser.carbs
    @calories = macroparser.calories

  end

  def show
    @user = User.find_by id: session[:user_id]
  end


  def notch_up
    @user = User.find_by id: session[:user_id]
    @user.notch += 1
    @user.save

    macroparser = MacroParser.new(@user.id)
    macroparser.parse!

    @user.fat = macroparser.fat
    @user.protein = macroparser.protein
    @user.carbs = macroparser.carbs
    @user.calories = macroparser.calories

    if @user.save
      redirect_to macros_path, notice: "Turned it up a notch!"
    else
      render :show, notice: "Something went wrong"
    end
  end


  def notch_down
    @user = User.find_by id: session[:user_id]
    @user.notch -= 1
    @user.save

    macroparser = MacroParser.new(@user.id)
    macroparser.parse!

    @user.fat = macroparser.fat
    @user.protein = macroparser.protein
    @user.carbs = macroparser.carbs
    @user.calories = macroparser.calories

    if @user.save
      redirect_to macros_path, notice: "Turned it down a notch!"
    else
      render :show, notice: "Something went wrong"
    end
  end


  def update
    @user = User.find_by id: session[:user_id]
    @user.weight_rate = params[:user][:weight_rate]
    @user.workout_count = params[:user][:workout_count]
    @user.workout_type = params[:user][:workout_type]
    @user.workout_intensity = params[:user][:workout_intensity]
    @user.notch = 0
    @user.save

    macroparser = MacroParser.new(@user.id)
    macroparser.parse!

    @user.fat = macroparser.fat
    @user.protein = macroparser.protein
    @user.carbs = macroparser.carbs
    @user.calories = macroparser.calories

    if @user.save
      redirect_to macros_path, notice: "Here's your results:"
    else
      render :edit
    end
  end

  def edit
    @user = User.find_by id: session[:user_id]
  end

end

app/views/macros/edit.html.erb
<div class="container">
  <br>
  <%= form_for @user, url:edit_macros_path do |f| %>

  <div class="col-sm-6 col-md-6 col-sm-offset-3 margin30">
      <div class="row">
        <div class="col-xs-12">
          <div class="form-group">
              <div class="row text-center">
                  <h3>Weight Goal</h3>
              </div>
          <%= f.select :weight_rate, options_for_select([
            ["Maintain Weight" , "Maintain"], ["Lose Weight" , "Lose"],
            ["Gain Weight", "Gain"]], selected = @user.weight_rate), {}, {class: "form-control"} %>
        </div>
      </div>
    </div>

    <hr class="form-divider">

    <div class="form-group">
        <div class="row text-center">
            <h3 class="workout-scheme">Workout Scheme</h3>
        </div>
        <div class="row text-center">
          <div class="col-xs-12">
              <div class="form-group">
                <div class="col-xs-12">
                  <%= f.label :workout_count, "Days per week" %>
                </div>
                <div class="col-xs-offset-4 col-xs-4">
                  <%= f.select :workout_count, options_for_select((0..7).step(1), selected = @user.workout_count), {}, { class:'form-control' } %>
                </div>
              </div>
          </div>

          <div class="col-xs-12">
              <div class="form-group">
                  <%= f.label :workout_intensity, "How Intense" %>
                  <div class="col-xs-12">
                    <%= f.select :workout_intensity, options_for_select([
                      ["Quick & Easy!" , 0.015], ["Tough Workouts Ahead." , 0.0325],
                      ["I Might Not Survive..." , 0.05], ["Hard Workouts Twice a Day" , 0.0875],
                      ], selected = @user.workout_intensity), {}, { class:'form-control' } %>
                  </div>
              </div>
          </div>
        </div>
    </div>


    <div class="form-group text-center">
        <strong>Exercise Type</strong>
        <div class="row">
            <div class="col-xs-4">
                <%= f.radio_button(:workout_type, "L", :checked => (true unless @user.workout_type != "L"), class: "radio-inline") %>
                <%= f.label(:workout_type, "Lifting")%>
            </div>
            <div class="col-xs-4">
              <%= f.radio_button(:workout_type, "C", :checked => (true unless @user.workout_type != "C"), class: "radio-inline") %>
                <%= f.label(:workout_type, "Cardio") %>
            </div>
            <div class="col-xs-4">
              <%= f.radio_button(:workout_type, "M", :checked => (true unless @user.workout_type != "M"), class: "radio-inline") %>
                <%= f.label(:workout_type, "Mixed") %>
            </div>
        </div>
    </div>
    <br>


    <div class="form-group">
        <%= f.submit "Calculate Macros!", class:'btn btn-danger btn-lg btn-block' %>
    </div>
    <% end %>
  </div>
</div>

app/views/macros/guest_macros.html.erb
<div class="container">
  <br> <br>
  <%= link_to new_user_path do %>
  <div class="row">
      <div class="col-sm-8 col-sm-offset-2 margin30">
          <div class="service-box wow animated fadeIn" data-wow-delay="0.1s">
              <i class="fa fa-calculator" aria-hidden="true"></i>
              <h4>Guest Nutrition Calculator</h4>
              <p>
                  Sign up and you won't have to fill this stuff again.
                  Just Tap here.
              </p>
          </div>
      </div>
      <% end %>
    </div>
    <% if @calories != 0 %>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 margin30">
            <div class="service-box wow animated fadeIn" data-wow-delay="0.15s">
                <i class="fa fa-cutlery" aria-hidden="true"></i>
                <p>
                  <h2>Daily Nutrition Goal:</h2>
                  <h3><%= @calories.round() %> Calories
                  <h3> <%= @protein %>g Protein
                  <h3> <%= @carbs %>g Carbs
                  <h3> <%= @fat %>g Fat </h3>
                  <hr>
                </p>
                  <h2>Simplified:</h2>
                  <h3> <%= ((@protein % 25) <= 13) ? (@protein / 25) : (@protein / 25) -1 %> Protein Portions
                  <h3> <%= ((@carbs % 25) <= 13) ? (@carbs / 25) : (@carbs / 25) -1 %> Carb Portions
                  <p></p>
                  <%= link_to about_path do %>
                  <div class="btn btn-danger">
                    How do I do this?
                  </div>
                  <% end %>
                  <p>

                  </p>

            </div>
        </div>
    </div>
    <% end %>
    <div class="row wow animated fadeIn" data-wow-delay="0.2s">
      <div class="container">
          <div class="col-sm-8 col-sm-offset-2">
                  <%= form_tag url: guest_macros_path do %>
                  <div class="form-group">
                      <div class="row">
                          <div class="col-xs-5">
                              <%= radio_button_tag(:gender, "M", true, :checked => (params[:gender] == "M"), class: "radio-inline") %>
                              <%= label_tag(:gender, "Male") %>
                          </div>
                          <div class="col-xs-5">
                              <%= radio_button_tag(:gender, "F", false, :checked => (params[:gender] == "F") , class: "radio-inline") %>
                              <%= label_tag(:gender, "Female") %>
                          </div>
                      </div>
                  </div>

                  <div class="form-group">
                      <div class="row">
                          <div class="col-xs-5">
                              <div class="form-group">
                                  <%= label_tag :age %>
                                  <%= number_field_tag :age, params[:age], class: "form-control"%>
                              </div>
                          </div>
                          <div class="col-xs-6">
                              <div class="form-group">
                                  <%= label_tag "Weight in lbs" %>
                                  <%= text_field_tag :weight, params[:weight], :step => 0.1, class: "form-control" %>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="form-group">
                      <div class="row">
                          <div class="col-xs-4">
                              <div class="form-group">
                                  <%= label_tag :height, "Height" %>
                                  <%= select_tag   :height, options_for_select((54..84).to_a
                                  .map { |inch| { id: inch.to_s, name: (inch/12).floor.to_s+'\''+(inch%12).to_s+'"'}}
                                  .collect{ |p| [p[:name], p[:id].to_i]}, selected = params[:height]), { class:'form-control' } %>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="form-group">
                    <div class="row">
                      <div class="col-xs-12">
                        <%= label_tag :weight_rate, "Weight Goal" %>
                        <%= select_tag :weight_rate, options_for_select([
                          ["Maintain Weight" , "Maintain"], ["Lose Weight" , "Lose"],
                          ["Gain Weight", "Gain"]], selected = params[:weight_rate]),
                        class: "form-control" %>
                      </div>
                    </div>
                  </div>

                  <hr class="form-divider">

                  <div class="form-group">
                      <div class="row text-center">
                          <strong>Workout Scheme</strong>
                      </div>
                      <div class="row text-center">
                        <div class="col-xs-5">
                            <div class="form-group">
                                <%= label_tag :workout_count, "Days per week" %>
                                <div class="col-xs-12">
                                  <%= select_tag :workout_count, options_for_select((0..7).step(1), selected = params[:workout_count]), class: "form-control" %>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-7">
                            <div class="form-group">
                                <%= label_tag :workout_intensity, "How Intense" %>
                                <div class="col-xs-12">
                                  <%= select_tag :workout_intensity, options_for_select([
                                    ["Quick & Easy" , 0.015], ["Tough Workouts Ahead." , 0.0325],
                                    ["I Might Not Survive..." , 0.05], ["Hard Workouts Twice a Day" , 0.0875],
                                    ], selected = params[:workout_intensity]), class: "form-control" %>
                                </div>
                            </div>
                        </div>
                      </div>
                  </div>


                  <div class="form-group text-center">
                      <strong>Exercise Type</strong>
                      <div class="row">
                          <div class="col-xs-4">
                              <%= radio_button_tag(:workout_type, "L", true, :checked => (params[:workout_type] == "L"), class: "radio-inline") %>
                              <%= label_tag(:workout_type, "Lifting")%>
                          </div>
                          <div class="col-xs-4">
                              <%= radio_button_tag(:workout_type, "C", false, :checked => (params[:workout_type] == "C"), class: "radio-inline") %>
                              <%= label_tag(:workout_type, "Cardio") %>
                          </div>
                          <div class="col-xs-4">
                              <%= radio_button_tag(:workout_type, "M", false, :checked => (params[:workout_type] == "M"), class: "radio-inline") %>
                              <%= label_tag(:workout_type, "Mixed") %>
                          </div>
                      </div>
                  </div>

                  <div class="form-group">
                      <%= submit_tag "Calculate Macros!", class:'btn btn-danger btn-lg btn-block' %>
                  </div>
                  <% end %>
        </div>
      </div>
    </div>
    <p></p>
    <p></p>
</div>

app/views/macros/show.html.erb
<div class="container">
  <br><br>
  <div class="text-center">
    <div class="col-sm-6 col-sm-offset-3 margin30">
        <div class="service-box wow animated fadeIn" data-wow-delay="0.1s">
            <i class="fa fa-cutlery" aria-hidden="true"></i>
            <% if @user.protein != nil %>
              <br>
              <p>
              <h2 class="workout-scheme">Daily Nutrition Goal:</h2><br>
              <h3> <%= @user.calories %> Calories<br>
              <h3> <%= @user.protein %>g Protein <br>
              <h3> <%= @user.carbs %>g Carbs <br>
              <h3> <%= @user.fat %>g Fat</h3>
               <hr>
              </p>
               <h2>Simplified:</h2>
               <h3> <%= ((@user.protein % 25) <= 13) ? (@user.protein / 25) : (@user.protein / 25) -1 %> Protein Portions
               <h3> <%= ((@user.carbs % 25) <= 13) ? (@user.carbs / 25) : (@user.carbs / 25) -1 %> Carb Portions
                 <p></p>
               <%= link_to about_path do %>
               <div class="btn btn-danger">
                 How do I do this?
               </div>
               <% end %>

                <% else %>

                  <div class="text-center">
                    <h2>
                      You don't have Macros yet<br> <br>
                      Let's get you some!
                    </h2>
                    <br>
                    <%= link_to "Okay!", edit_macros_path, class: "btn, btn-lg btn-primary" %>
                  </div>

                <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 text-center">
        <%= link_to "Recalculate", edit_macros_path, class: "btn, btn-lg btn-danger" %>
            <p></p>
    </div>

    </div>



</div>

                      <!-- <br>
                      Notch: <br>
                       <%= link_to notch_down_path, method: "patch" do %>
                       <div class="notch-buttons">
                          <i class="fa fa-arrow-circle-down" aria-hidden="true"></i>
                       </div>

                         <% end %>

                       <%= (@user.notch * 10).to_i %>

                      <%= link_to notch_up_path, method: "patch" do %>
                      <i class="fa fa-arrow-circle-up notch-buttons" aria-hidden="true"></i>
                      <% end %>
                      <br>
                      <br> -->