config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'


  get 'about' => 'welcome#about', as: :about
  get 'coaching' => 'welcome#coaching', as: :coaching


  get 'guestmacros' => 'macros#guest_macros', as: :guest_macros
  post 'guestmacros' => 'macros#guest_macros'

  get 'macros' => 'macros#show', as: :macros
  get 'macros/edit' => 'macros#edit', as: :edit_macros
  patch 'macros/edit' => 'macros#update'
  patch 'macros/up' => 'macros#notch_up', as: :notch_up
  patch 'macros/down' => 'macros#notch_down', as: :notch_down


  post 'mealplans' => 'mealplans#auto_mealplans', as: :auto_mealplans
  patch 'mealplans/generate/:id' => 'mealplans#generate', as: :generate_mealplan
  get 'mealplans' => 'mealplans#list', as: :mealplans
  post 'mealplans' => 'mealplans#new', as: :new_mealplan
  get 'mealplans/:id' => 'mealplans#show', as: :mealplan
  get 'mealplans/edit/:id' => 'mealplans#edit', as: :edit_mealplan
  delete 'mealplans/:id' => 'mealplans#delete_mealplan', as: :delete_mealplan
  patch 'mealplans/edit/:id' => 'mealplans#add_meal', as: :add_meal
  delete 'mealplans/:id/meals/:meal_id' => 'mealplans#delete_meal', as: :delete_meal


  get 'meal/:id' => 'food#show_meal', as: :meal
  get 'ingredient/:id' => 'food#show_ingredient', as: :ingredient
  get 'mealcenter' => 'food#mealcenter', as: :mealcenter
  get 'foodfinder' => 'food#finder', as: :food_finder
  post 'foodfinder' => 'food#search', as: :search_food
  post 'favorites' => 'food#add_favorite', as: :add_favorite
  get 'favorites' => 'food#favorites', as: :favorites
  delete 'favorites/:id' => 'food#delete_favorite', as: :delete_favorite
  get 'recipecollections' => 'food#recipe_collections', as: :recipe_collections
  get 'recipe/:id' => 'food#show_recipe', as: :recipe


  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user
  get 'profile' => 'users#profile', as: :user_profile
  get 'profile/edit' => 'users#edit_profile', as: :edit_profile
  patch 'profile/edit' => 'users#update_profile'


  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#destroy'





end

app/models/mealplan.rb
class Mealplan < ActiveRecord::Base
  belongs_to :user
  has_many :meals



  def quantity
  end


  ## Must refactor this code ##

  def kcals
    meal_ids = meals.pluck(:recipe_id)
    recipes = Recipe.where id: meal_ids
    recipes.map(&:kcals).sum

    recipe_stats = meals.map do |meal|
      { quantity: meal.quantity, kcals: meal.recipe.kcals }
    end

    recipe_stats.map { |s| s[:quantity] * s[:kcals] }.sum
  end

  def proteins
    meal_ids = meals.pluck(:recipe_id)
    recipes = Recipe.where id: meal_ids
    recipes.map(&:proteins).sum

    recipe_stats = meals.map do |meal|
      { quantity: meal.quantity, proteins: meal.recipe.proteins }
    end

    recipe_stats.map { |s| s[:quantity] * s[:proteins] }.sum
  end

  def carbs
    meal_ids = meals.pluck(:recipe_id)
    recipes = Recipe.where id: meal_ids
    recipes.map(&:carbs).sum

    recipe_stats = meals.map do |meal|
      { quantity: meal.quantity, carbs: meal.recipe.carbs }
    end

    recipe_stats.map { |s| s[:quantity] * s[:carbs] }.sum
  end

  def fats
    meal_ids = meals.pluck(:recipe_id)
    recipes = Recipe.where id: meal_ids
    recipes.map(&:fats).sum

    recipe_stats = meals.map do |meal|
      { quantity: meal.quantity, fats: meal.recipe.fats }
    end

    recipe_stats.map { |s| s[:quantity] * s[:fats] }.sum
  end

end

app/controllers/mealplans_controller.rb
class MealplansController < ApplicationController

  before_action :authenticate_user!

  before_action do
    if @current_user.age == nil
      redirect_to edit_profile_path, alert: "We're gonna need this info first!"
    elsif @current_user.protein == nil
      redirect_to edit_macros_path, alert: "We're gonna need this info first!"
    end
  end

  def list
    @mealplans = @current_user.mealplans
    @recipes = Recipe.where.not("category ~* ?", "^[0-9]")
    @collection_names = @recipes.pluck(:collection).uniq

  end

  def new
    if params[:name] == ""
      mealplan_number = @current_user.mealplans.size + 1
      @mealplan = Mealplan.new
      @mealplan.user_id = @current_user.id
      @mealplan.name = "Day #{mealplan_number}"
    else
      @mealplan = Mealplan.new
      @mealplan.user_id = @current_user.id
      @mealplan.name = params[:name]
    end
    if @mealplan.save
      redirect_to edit_mealplan_path(id: @mealplan.id)
    else
      flash[:notice] = "Something went wrong"
      render :list
    end
  end

  def show
    @mealplan = Mealplan.find_by id: params[:id]
  end

  def edit
    @mealplan = Mealplan.find_by id: params[:id]
    @meals = @mealplan.meals

    @remaining_calories = @current_user.calories - @mealplan.kcals
    @remaining_protein = @current_user.protein - @mealplan.proteins
    @remaining_carbs = @current_user.carbs - @mealplan.carbs
    @remaining_fat = @current_user.fat - @mealplan.fats

    @collection_recipes = Recipe.where.not("category ~* ?", "^[0-9]")
    @user_favorites = Recipe.where(category: (@current_user.id).to_s)

    @recipes = @collection_recipes.or(@user_favorites)

  end

  def delete_mealplan
    @mealplan = Mealplan.find_by id: params[:id]
    @mealplan.destroy
    redirect_to mealplans_path, notice: "Mealplan Deleted"
  end

  def add_meal
    @recipes = Recipe.all
    # @recipes = Recipe.where.not("category ~* ?", "^[0-9]")
    # current_user_recipe Recipe.where(category: @current_user.id.to_s)
    # shovel operation 2 into array number 1
    @mealplan = Mealplan.find_by id: params[:id]
    @new_meal = Meal.new
    @new_meal.mealplan_id = @mealplan.id
    @new_meal.recipe_id = params[:mealplan][:meals]
    @new_meal.quantity = params[:mealplan][:quantity]

    unless params[:mealplan][:meals].present?
      redirect_to edit_mealplan_path(id: @mealplan.id), notice: "You have to select a meal to add"
    else
      @remaining_calories = @current_user.calories - @mealplan.kcals - @new_meal.kcals

      if @remaining_calories < 0
        redirect_to edit_mealplan_path(id: @mealplan.id), notice: "That's too many calories, remove something first before adding this meal"
      elsif @new_meal.save && @remaining_calories > 0
        redirect_to edit_mealplan_path, notice: "Meal Added"
      else
        flash[:notice] = "Oops! Something went wrong... Try again?"
        render :edit
      end
    end
  end

  def delete_meal
    @meal = Meal.find_by id: params[:meal_id]
    @meal.destroy
    redirect_to edit_mealplan_path(params[:id]), notice: "Meal Deleted"
  end

  def generate
    @mealplan = Mealplan.find_by id: params[:id]
    auto_mealplans = MealplanParser.new(@current_user.id)
    auto_mealplans.generate!(@mealplan.id)
    redirect_to mealplan_path(id:@mealplan.id), notice: "Mealplan Created!"
  end

  def auto_mealplans
    if params[:collection] == ""
      redirect_to mealplans_path, notice: "You have to select a Recipe Collection"
    else
      auto_mealplans = MealplanParser.new(@current_user.id)
      auto_mealplans.generate_collection!(params[:collection])
      redirect_to mealplans_path, notice: "Mealplans Created!"
    end
  end

end

app/views/mealplans/edit.html.erb
<div class="container container-edit">
  <br>
  <div class="wow animated fadeIn text-center" data-wow-delay="0.1s">
    <h2 class="mealplan-title"> <%= @mealplan.name %> </h2>
  </div>

  <div class="wow animated fadeIn text-center" data-wow-delay="0.2s">
    <%= form_for @mealplan, url: add_meal_path do |f| %>
    <div class="form-group text-center">
      <div class="row">
        <div class="col-xs-5 col-md-offset-1 col-md-5">
          <div class="form-group">
            <%= f.collection_select :meals, @recipes, :id, :name, {:include_blank => "Meal List"}, { class:'form-control' } %>
          </div>
        </div>
        <div class="col-xs-3 col-md-1">
          <%= f.select :quantity, options_for_select((1..10).step(1), selected = 1), {}, {class: "form-control"} %>
        </div>
        <div class="text-center">
            <div class="col-xs-4 col-md-4">
              <%= f.submit "Add Meal", class:"btn btn-success btn-block" %>
            </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
 <br>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 margin30 meals wow animated fadeIn" data-wow-delay="0.3s">
      <% @mealplan.meals.each do |meal|%>
        <div class="col-xs-12">
          <strong class="meal-title">
            <%= link_to meal.recipe.name, meal_path(id: meal.id)%>
            <small>
              <%= link_to "x", delete_meal_path(@mealplan.id, meal.id ), method: :delete %>
            </small>
          </strong>
          <span class="meal-body">
            <% meal.recipe.recipeparts.each do |part| %>
          <br>
            <%= pluralize(number_to_human((part.amount * part.ingredient.serving_amount) * meal.quantity), part.ingredient.serving_name) %> <%= part.ingredient.name %>
          <% end %>
          </span>
          <hr>
        </div>

      <% end %>
    </div>
  </div>
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <%= link_to mealplan_path(id: @mealplan.id) do %>
        <div class="btn btn-success btn-block">
          Go Back
        </div>
        <% end %>
      </div>


      <!-- For Future Autocomplete Feature! Maybe! -->
      <!-- <div class="col-xs-6">
        <%= form_for @mealplan, url: generate_mealplan_path(id: @mealplan.id) do |f| %>
        <div class="form-group">
            <div class="text-center">
                  <%= f.submit "Auto-Complete", class:"btn btn-success btn-block" %>
            </div>
          </div>
        <% end %>
      </div> -->
    </div>
</div>


  <div class="macro-footer text-center">
    <div class="row text-center">
    <strong>Remaining</strong>
    </div>
    <div class="row">
      <div class="col-xs-3">
          <strong><span class="macro-footer-text-kcals"><%= @remaining_calories.round(0) %>kcal</span></strong>
      </div>
      <div class="col-xs-3">
          <span class="macro-footer-text">P:
          <%= number_to_human(@remaining_protein) %>g</span>
      </div>
      <div class="col-xs-3">
          <span class="macro-footer-text">C:
          <%= number_to_human(@remaining_carbs) %>g</span>
      </div>
      <div class="col-xs-3">
          <span class="macro-footer-text">F:
          <%= number_to_human(@remaining_fat) %>g</span>
      </div>
    </div>
  </div>

app/views/mealplans/list.html.erb
<div class="container">
  <br>
  <div class="text-center">
    <div class="wow animated fadeIn" data-wow-delay="0.1s">
      <h2 class="mealplan-title mealplan-title-bottom-padding">Your Mealplans</h2>
      <hr class="form-divider">
    </div>
    <br>
    <div class="wow animated fadeIn" data-wow-delay="0.15s">
      <% @mealplans.each do |mealplan| %>
      <h3><%= link_to mealplan.name, mealplan_path(id: mealplan.id) %>
        <small><%= link_to "x", delete_mealplan_path(mealplan.id), method: :delete %></small> <br>
      </h3>
        <% end %>
    </div>

  </div>

  <br>
  <hr class="form-divider wow animated fadeIn" data-wow-delay="0.2s">
  <div class="row wow animated fadeIn" data-wow-delay="0.2s">
    <div class="col-xs-6">
      <%= form_tag(url: auto_mealplans_path) do |f| %>
        <div class="form-group">
          <div class="text-center">
            <%= submit_tag "Auto Meal Plans", class:"btn btn-danger btn-block" %>
          </div>
        </div>
    </div>
    <div class="col-xs-6">
      <div class="form-group">
        <%= select_tag :collection, options_for_select(@collection_names),
         {prompt: "Select Collection", class: "form-control"}%>
      </div>
    </div>
  </div>
  <% end %>


  <!-- For future custom meal creation -->
  <!-- <strong><h4 class="text-center wow animated fadeIn" data-wow-delay="0.25s">- or - </h4></strong>
  <div class="row wow animated fadeIn" data-wow-delay="0.3s">
    <div class="col-xs-6">
      <%= form_tag(url: new_mealplan_path) do |f| %>
        <div class="form-group">
          <div class="text-center">
            <%= submit_tag "Create Your Own", class:"btn btn-danger btn-block" %>
          </div>
        </div>
    </div>
    <div class="col-xs-6">
      <div class="form-group">
          <%= text_field_tag :age, nil, placeholder:"Give it a name", class: "form-control"%>
      </div>
    </div>
  </div>
  <% end %> -->


  </div>
</div>

app/views/mealplans/show.html.erb
<div class="container">
  <br>
  <div class="col-sm-10 col-sm-offset-1 margin30 text-center">
    <h2 class="mealplan-title"> <%= @mealplan.name %> <small>
      <span class="smaller-text"> <%= link_to "edit", edit_mealplan_path(@mealplan.id) %></span></small></h2>
  </div>
  <br>

  <div class="row">
      <% @mealplan.meals.each do |meal|%>
    <div class="col-sm-6 col-sm-offset-6 margin30 meals">
      <strong class="meal-title">
        <%= link_to meal.recipe.name, meal_path(id: meal.id)%>
      </strong>


      <span class="meal-body">
        <% meal.recipe.recipeparts.each do |part| %>
        <br>
          <%= pluralize(number_to_human((part.amount * part.ingredient.serving_amount) * meal.quantity), part.ingredient.serving_name) %> <%= part.ingredient.name %>
        <% end %>
      </span>
      <hr>
    </div>

    <% end %>
  </div>
  <br>

  <div class="row">
    <div class="col-xs-offset-3 col-xs-6 col-md-offset-0">
      <%= link_to mealplans_path do %>
      <div class="btn btn-success btn-block">
        Back
      </div>
      <p></p>
      <% end %>
    </div>
  </div>
</div>