config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'


  get 'about' => 'welcome#about', as: :about
  get 'coaching' => 'welcome#coaching', as: :coaching


  get 'guestmacros' => 'macros#guest_macros', as: :guest_macros
  post 'guestmacros' => 'macros#guest_macros'

  get 'macros' => 'macros#show', as: :macros
  get 'macros/edit' => 'macros#edit', as: :edit_macros
  patch 'macros/edit' => 'macros#update'
  patch 'macros/up' => 'macros#notch_up', as: :notch_up
  patch 'macros/down' => 'macros#notch_down', as: :notch_down


  post 'mealplans' => 'mealplans#auto_mealplans', as: :auto_mealplans
  patch 'mealplans/generate/:id' => 'mealplans#generate', as: :generate_mealplan
  get 'mealplans' => 'mealplans#list', as: :mealplans
  post 'mealplans' => 'mealplans#new', as: :new_mealplan
  get 'mealplans/:id' => 'mealplans#show', as: :mealplan
  get 'mealplans/edit/:id' => 'mealplans#edit', as: :edit_mealplan
  delete 'mealplans/:id' => 'mealplans#delete_mealplan', as: :delete_mealplan
  patch 'mealplans/edit/:id' => 'mealplans#add_meal', as: :add_meal
  delete 'mealplans/:id/meals/:meal_id' => 'mealplans#delete_meal', as: :delete_meal


  get 'meal/:id' => 'food#show_meal', as: :meal
  get 'ingredient/:id' => 'food#show_ingredient', as: :ingredient
  get 'mealcenter' => 'food#mealcenter', as: :mealcenter
  get 'foodfinder' => 'food#finder', as: :food_finder
  post 'foodfinder' => 'food#search', as: :search_food
  post 'favorites' => 'food#add_favorite', as: :add_favorite
  get 'favorites' => 'food#favorites', as: :favorites
  delete 'favorites/:id' => 'food#delete_favorite', as: :delete_favorite
  get 'recipecollections' => 'food#recipe_collections', as: :recipe_collections
  get 'recipe/:id' => 'food#show_recipe', as: :recipe


  get 'registration' => 'users#new', as: :new_user
  post 'registration' => 'users#create', as: :create_user
  get 'profile' => 'users#profile', as: :user_profile
  get 'profile/edit' => 'users#edit_profile', as: :edit_profile
  patch 'profile/edit' => 'users#update_profile'


  get 'sign_in' => 'sessions#new', as: :sign_in
  post 'sign_in' => 'sessions#create'
  delete 'sign_in' => 'sessions#destroy'





end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Meal Slice</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/44d0d3ac87.js"></script>
    <%= csrf_meta_tags %>



  </head>

  <body>


    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to root_path do %>
          <%=  image_tag("mealslicelogo.png", class:"navbar-left navbar-logo")%>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right">
            <% if @current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", user_profile_path %></li>
                <li class=""> <%= link_to "In Development", mealcenter_path %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign Out", sign_in_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
                <%= link_to "Sign In", sign_in_path, class: "btn btn-danger navbar-btn btn-spacer signin-button" %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if @current_user %>
            <li class=""> <%= link_to "My Nutrition", macros_path %>
            <% else %>
            <li class=""> <%= link_to "Nutrition Calculator", guest_macros_path %>
            <% end %>
            <li class=""> <%= link_to "Guides/Info", about_path %>
            <li class=""> <%= link_to "Coaching", coaching_path %>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>




    <div class="container">
  <% if notice %>
    <br>
    <div class="alert alert-danger text-center alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <br>
    <div class="alert alert-danger text-center alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= alert %>
    </div>
  <% end %>
</div>

    <%= yield %>


  </body>
</html>